INSERT INTO "LunchOrder_ingredient" VALUES(1,'Ham','M');
INSERT INTO "LunchOrder_ingredient" VALUES(2,'Turkey','M');
INSERT INTO "LunchOrder_ingredient" VALUES(3,'Hummus','M');
INSERT INTO "LunchOrder_ingredient" VALUES(4,'Kidney Beans','M');
INSERT INTO "LunchOrder_ingredient" VALUES(5,'American','CH');
INSERT INTO "LunchOrder_ingredient" VALUES(6,'Provolone','CH');
INSERT INTO "LunchOrder_ingredient" VALUES(7,'Swiss','CH');
INSERT INTO "LunchOrder_ingredient" VALUES(8,'Lettuce','V');
INSERT INTO "LunchOrder_ingredient" VALUES(9,'Spinace','V');
INSERT INTO "LunchOrder_ingredient" VALUES(10,'Cucumbers','V');
INSERT INTO "LunchOrder_ingredient" VALUES(11,'Red Pepper','V');
INSERT INTO "LunchOrder_ingredient" VALUES(12,'Green Pepper','V');
INSERT INTO "LunchOrder_ingredient" VALUES(13,'Olives','V');
INSERT INTO "LunchOrder_ingredient" VALUES(14,'Carrots','V');
INSERT INTO "LunchOrder_ingredient" VALUES(15,'Tomato','V');
INSERT INTO "LunchOrder_ingredient" VALUES(16,'Banana Pepper','V');
INSERT INTO "LunchOrder_ingredient" VALUES(17,'Pickles','V');
INSERT INTO "LunchOrder_ingredient" VALUES(18,'Oregano','V');
INSERT INTO "LunchOrder_ingredient" VALUES(19,'Mayo','C');
INSERT INTO "LunchOrder_ingredient" VALUES(20,'Mustard','C');
INSERT INTO "LunchOrder_ingredient" VALUES(21,'Brown Mustard','C');
INSERT INTO "LunchOrder_ingredient" VALUES(22,'Dijonnaise','C');
INSERT INTO "LunchOrder_ingredient" VALUES(23,'Ranch','D');
INSERT INTO "LunchOrder_ingredient" VALUES(24,'Balsamic','D');
INSERT INTO "LunchOrder_ingredient" VALUES(25,'Italian','D');
INSERT INTO "LunchOrder_ingredient" VALUES(26,'Blue Cheese','D');
INSERT INTO "LunchOrder_ingredient" VALUES(27,'Honey Mustard','D');
INSERT INTO "LunchOrder_ingredient" VALUES(28,'Kidney Beans','M');
INSERT INTO "LunchOrder_ingredient" VALUES(29,'Turkey','WS');
INSERT INTO "LunchOrder_ingredient" VALUES(30,'Bacon','WS');
INSERT INTO "LunchOrder_ingredient" VALUES(31,'Ham','WS');
INSERT INTO "LunchOrder_ingredient" VALUES(32,'Tomato','WS');
INSERT INTO "LunchOrder_ingredient" VALUES(33,'Lettuce','WS');
INSERT INTO "LunchOrder_ingredient" VALUES(34,'Chocolate Chip','CO');
INSERT INTO "LunchOrder_ingredient" VALUES(35,'Oatmeal Raisin','CO');
INSERT INTO "LunchOrder_ingredient" VALUES(36,'Macedamia Nut','CO');

